sudo: false
language: java
jdk:
  - oraclejdk7
  - oraclejdk8
branches:
  only:
    - master
    - orika-1.5.x

notifications:
  recipients:
    - elaatifi@gmail.com
    - matt.deboer@gmail.com
  email:
    on_success: always
    on_failure: always
